# Generated by Django 4.1.4 on 2022-12-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_visitants'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitants',
            name='black_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitants',
            name='number_visits',
            field=models.IntegerField(default=0),
        ),
    ]
